/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import model.Cliente;
import model.Mensagem;

/**
 *
 * @author emersant
 */
public class TelaCliente extends javax.swing.JFrame implements ActionListener{

    private Boolean conectado = false;
    private Integer portaPadrao;
    private String servidorPadrao;
    private Cliente cliente;
    /**
     * Creates new form TelaServidor
     * @param porta
     * @param servidor
     */
    public TelaCliente(Integer porta, String servidor) {
        super("Chat Cliente");
        portaPadrao = porta;
        servidorPadrao = servidor;
        initComponents();
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setSize(600, 700);
        setVisible(true);
        textNomeAndMsg.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNorte = new javax.swing.JPanel();
        panelConexao = new javax.swing.JPanel();
        labelServidor = new javax.swing.JLabel();
        labelPorta = new javax.swing.JLabel();
        textServidor = new javax.swing.JTextField();
        textPorta = new javax.swing.JTextField();
        textNomeAndMsg = new javax.swing.JTextField();
        labelNome = new javax.swing.JLabel();
        buttonEnviar = new javax.swing.JButton();
        panelChat = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textChat = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        panelSul = new javax.swing.JPanel();
        buttonLogin = new javax.swing.JButton();
        buttonLogout = new javax.swing.JButton();
        buttonOnlines = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 600));

        labelServidor.setText("Endereço do servidor:");

        labelPorta.setText("Porta:");

        textServidor.setText("localhost");

        textPorta.setText("6970");

        javax.swing.GroupLayout panelConexaoLayout = new javax.swing.GroupLayout(panelConexao);
        panelConexao.setLayout(panelConexaoLayout);
        panelConexaoLayout.setHorizontalGroup(
            panelConexaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConexaoLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(labelServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(labelPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        panelConexaoLayout.setVerticalGroup(
            panelConexaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConexaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelConexaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelServidor)
                    .addComponent(labelPorta)
                    .addComponent(textServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textPorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        textNomeAndMsg.setText("Anônimo");

        labelNome.setText("Digite seu nome aqui");

        buttonEnviar.setText("Enviar");

        javax.swing.GroupLayout panelNorteLayout = new javax.swing.GroupLayout(panelNorte);
        panelNorte.setLayout(panelNorteLayout);
        panelNorteLayout.setHorizontalGroup(
            panelNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelConexao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNorteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textNomeAndMsg))
                .addGap(18, 18, 18)
                .addComponent(buttonEnviar)
                .addContainerGap())
        );
        panelNorteLayout.setVerticalGroup(
            panelNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNorteLayout.createSequentialGroup()
                .addComponent(panelConexao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(labelNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNomeAndMsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonEnviar))
                .addContainerGap())
        );

        textChat.setColumns(20);
        textChat.setRows(5);
        textChat.setText("Bem-vindo a sala de Chat!\n");
        jScrollPane1.setViewportView(textChat);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout panelChatLayout = new javax.swing.GroupLayout(panelChat);
        panelChat.setLayout(panelChatLayout);
        panelChatLayout.setHorizontalGroup(
            panelChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelChatLayout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelChatLayout.setVerticalGroup(
            panelChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChatLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );

        buttonLogin.setText("Login");
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });

        buttonLogout.setText("Logout");
        buttonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogoutActionPerformed(evt);
            }
        });

        buttonOnlines.setText("Usuários Online");
        buttonOnlines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOnlinesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSulLayout = new javax.swing.GroupLayout(panelSul);
        panelSul.setLayout(panelSulLayout);
        panelSulLayout.setHorizontalGroup(
            panelSulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSulLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonLogin)
                .addGap(61, 61, 61)
                .addComponent(buttonLogout)
                .addGap(71, 71, 71)
                .addComponent(buttonOnlines)
                .addGap(113, 113, 113))
        );
        panelSulLayout.setVerticalGroup(
            panelSulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSulLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonLogin)
                    .addComponent(buttonLogout)
                    .addComponent(buttonOnlines))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSul, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelNorte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelChat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelNorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelChat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed
        String nomeUsuario = textNomeAndMsg.getText().trim();
        if(nomeUsuario.length() == 0)
                return;
        String servidor = textServidor.getText().trim();
        if(servidor.length() == 0)
                return;
        String numeroDaPorta = textPorta.getText().trim();
        if(numeroDaPorta.length() == 0)
                return;
        int porta = 0;
        try {
                porta = Integer.parseInt(numeroDaPorta);
        }
        catch(Exception en) {
                return;
        }

        cliente = new Cliente(servidor, porta, nomeUsuario, this);

        if(!cliente.iniciar()) 
                return;
        textNomeAndMsg.setText("");
        labelNome.setText("Digite sua mensagem abaixo");
        conectado = true;

        buttonLogin.setEnabled(false);
        buttonLogout.setEnabled(true);
        buttonOnlines.setEnabled(true);
        textServidor.setEditable(false);
        textPorta.setEditable(false);
        textNomeAndMsg.addActionListener(this);
    }//GEN-LAST:event_buttonLoginActionPerformed

    private void buttonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogoutActionPerformed
        cliente.enviarMensagem(new Mensagem(Mensagem.LOGOUT, ""));
    }//GEN-LAST:event_buttonLogoutActionPerformed

    private void buttonOnlinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOnlinesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonOnlinesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TelaCliente(6970, "localhost").setVisible(true);
            }
        });
    }
    
     public void append(String str) {
        textChat.append(str);
        textChat.setCaretPosition(textChat.getText().length());
	}
    public void connectionFailed() {
        buttonLogin.setEnabled(true);
        buttonLogout.setEnabled(false);
        buttonOnlines.setEnabled(false);
        labelNome.setText("Digite seu nome de usuário abaixo");
        textNomeAndMsg.setText("Anônimo");
        textPorta.setText("" + portaPadrao);
        textServidor.setText(servidorPadrao);
        textServidor.setEditable(false);
        textPorta.setEditable(false);
        textNomeAndMsg.removeActionListener(this);
        conectado = false;
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEnviar;
    private javax.swing.JButton buttonLogin;
    private javax.swing.JButton buttonLogout;
    private javax.swing.JButton buttonOnlines;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelPorta;
    private javax.swing.JLabel labelServidor;
    private javax.swing.JPanel panelChat;
    private javax.swing.JPanel panelConexao;
    private javax.swing.JPanel panelNorte;
    private javax.swing.JPanel panelSul;
    private javax.swing.JTextArea textChat;
    private javax.swing.JTextField textNomeAndMsg;
    private javax.swing.JTextField textPorta;
    private javax.swing.JTextField textServidor;
    // End of variables declaration//GEN-END:variables

    public Boolean getConectado() {
        return conectado;
    }

    public void setConectado(Boolean conectado) {
        this.conectado = conectado;
    }

    public Integer getPortaPadrao() {
        return portaPadrao;
    }

    public void setPortaPadrao(Integer portaPadrao) {
        this.portaPadrao = portaPadrao;
    }

    public String getServidorPadrao() {
        return servidorPadrao;
    }

    public void setServidorPadrao(String servidorPadrao) {
        this.servidorPadrao = servidorPadrao;
    }

    public Cliente getCliente() {
        return cliente;
    }

    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
